name: Github Action Git Tag Test

on:
  push:
    tags:
      - '*'

jobs:
  github-action-git-tag-test:
    name: Github Action Git Tag Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Write version to file
        if: startsWith(github.ref, 'refs/tags')
        run: echo "__version__ = '$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/[v,V]//g')'" > __version__.py && cat __version__.py